[package]
name = "fahrenheit_celsius_convert"
version = "0.1.0"
edition = "2023"
authors = ["Nayantha Yasiru nayanthayasiru@gmail.com"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
